### ISSUE TITLE
Got an error with 0.2.5

### ISSUE THREAD

**Issue by Sabre8073** [Engarak/MiiShop#1]
Tried the new version and got this error.

[MiiShop_5-1-19-04_37_34.log](https://github.com/Engarak/MiiShop/files/3136303/MiiShop_5-1-19-04_37_34.log)

**Comment by Engarak** [comment]
I'm looking at this and see a bug in my code...nothing like hardcoding something.  Explains why it worked for me! :/  I'll fix this and get a 0.2.6 up for you to try shortly.

**Comment by Engarak** [comment]
Can you let me know if the [new version](https://github.com/Engarak/MiiShop/releases/tag/0.2.6) works for you that I just posted?  The same miiShop_installer should work, just run it as an upgrade.

**Comment by Sabre8073** [comment]
Ok so I got an error using the installer when I chose to upgrade, I therefore deleted all files other than the updater and got a smooth install afterwards but still getting an error when running the program. I like the idea of this and want to help as much as possible because uploading to mediafire and creating QRs is to long of a process. Keep up the good work!

[MiiShop_5-2-19-08_44_16.log](https://github.com/Engarak/MiiShop/files/3138554/MiiShop_5-2-19-08_44_16.log)

**Comment by Engarak** [comment]
Ok, I think i see the issue...can you replace your miiShop.ps1 file with the one in this zip file and let me know if it fixes the issue?
[miishop.zip](https://github.com/Engarak/MiiShop/files/3140539/miishop.zip)

**Comment by Sabre8073** [comment]
Still getting an error seems to be around the same spot. I hope this is helping you fix other peoples errors and not just my own. Again keep up the good work, I like where this is going and hope to see it to fruition.


[MiiShop_5-3-19-06_40_40.log](https://github.com/Engarak/MiiShop/files/3141893/MiiShop_5-3-19-06_40_40.log)

**Comment by SouDescolado** [comment]
Is the "3ds stuff" a folder you created? If so, try changing the name to "3ds-stuff".

**Comment by Sabre8073** [comment]
That fixed that issue but now when I go to the http://localhost:8080, I'm getting file not found.


[MiiShop_5-3-19-09_35_24.log](https://github.com/Engarak/MiiShop/files/3142576/MiiShop_5-3-19-09_35_24.log)

**Comment by SouDescolado** [comment]
The only file not found is the Madden one. Is it possible for you to test without it?

**Comment by Sabre8073** [comment]
According to the log everything seems to be working perfectly after removing Madden but I'm still receiving a File not found. Therefore, it maybe on my end but I'm not sure where.


[MiiShop_5-3-19-02_36_20.log](https://github.com/Engarak/MiiShop/files/3143494/MiiShop_5-3-19-02_36_20.log)

![Filenotfound](https://user-images.githubusercontent.com/7695054/57164652-03fc8d80-6db2-11e9-9a89-5bd1f7327b36.jpg)

**Comment by Engarak** [comment]
add main.html at the end of the url so it should be http://localhost:8080/main.html .  Also, make sure you're pulling this up on the computer you're running miiShop on if you use localhost.  If you're opening it on another computer on your network go to http://192.168.1.69:8080/main.html

**Comment by Engarak** [comment]
> The only file not found is the Madden one. Is it possible for you to test without it?

Actually the issue with the 404 error is that it got information about the game, but wasn't able to pull any boxart.  It's not a huge deal but I'd like to know the game file name for madden, as it should work, but may have some case I didn't think to account for.

**Comment by Sabre8073** [comment]
Nice! Adding main at the end of the ip address worked but you are correct that a few cias that I have are not portraying boxart or the QR code to include "Madden NFL Football.cia"

**Comment by Engarak** [comment]
Can you get me the exact file names of the ones that don't have art or QR code?  I can understand not having art but I don't get it not having a QR code as that should be built when you put the game in the folder where miiShop.ps1 exists.

**Comment by Sabre8073** [comment]
Sorry for the late reply been busy, here is the list spelled exactly like in the folder.

Detective Pikachu.cia (Has Boxart no QR code)
How to Train Your Dragon 2.cia (Has Boxart no QR code)
Luigi's Mansion 2.cia (No Boxart and no QR code)
Mario Kart 7.cia (Has Boxart no QR code)
Sega 3D Classics Collection.cia (Has Boxart no QR code)
Tomodachi Life.cia (Has Boxart no QR code)
Wreck-it Ralph.cia (Has Boxart no QR code)

**Comment by Engarak** [comment]
So those all should match if they are in the DB, and they ALL should make a QR code, no matter if things match or not.  I wonder if things didn't get made properly.  If you go to the folder where miiShop.ps1 is, delete the main.html, and the qr folder and start it back up.  Let me know if that resolves the issue, if it doesn't can you send me your main.html and your latest log file and I can see what broke down for some reason.

**Comment by Sabre8073** [comment]
Done what you asked and it was with the same outcome...I'll post a SS with this

![MiiShop](https://user-images.githubusercontent.com/7695054/57467586-06426a00-7240-11e9-84bc-f2309c6e3ce8.jpg)

**Comment by Engarak** [comment]
Hmm...can you send me your `main.html` file and latest miiShop_[date].log file?   I see it's not working, so that makes me curious why as I can't replicate this yet.  Oh, and your game names are perfect.

**Comment by Sabre8073** [comment]
Here you go


[Miishop Issues.zip](https://github.com/Engarak/MiiShop/files/3167072/Miishop.Issues.zip)

**Comment by Engarak** [comment]
ok, I think I see what happened, and I think this can be fixed by replacing your miiShop.ps1 file with the one in the zip file attached to this post.  

So this will fix when the QR codes are built, but it will currently rebuild the QR codes each time you start up, not just on the first run.  The good news is this should fix the issue, and it's a patch for now as the next version I'm working on, I think I'll store this information into the database.
  
[miishop2.6.1.zip](https://github.com/Engarak/MiiShop/files/3168664/miishop2.6.1.zip)

**Comment by Sabre8073** [comment]
Same scenario, nothing changed but I can install the QRs from the folder just not from the localhost. I've tried multiple browsers thinking that may be the issue but still doesn't have QRs showing up on localhost.

**Comment by Engarak** [comment]
What happens if you go to http://192.168.1.69:8080/main.html?  Do the QR codes load when you go there?

**Comment by Sabre8073** [comment]
That didn't work either. I'm just glad to have the QRs in the folder, but if you want to continue troubleshooting, I'm here to assist.

**Comment by Engarak** [comment]
Well I want it to work for you, but it's up to you how deep you want to go.  That said, the QR codes are no good if the webserver isn't working.  Can you see if the QR codes work for you at any point?

**Comment by Sabre8073** [comment]
yea the QRs didn't work

**Comment by Kirezar** [comment]
I was having the same error, but looking into your code it was a pretty easy fix. You're giving out the QRs with the original names and blank spaces, instead of the sanitized ones, like you did for the cias.

All I did was move around some lines and changing what variables it uses. So from 

    #Make game names display in the list as more readable, and removing our reformatting.  
    $gameDisplayName = get-CleanGamename($3dsCiafile.name)            
    Write-Output ('{0} Making QR code for {1}' -f $(Get-Date -Format s),$gameDisplayName)
    New-QR -Message ('http://{0}:8080/cias/{1}' -f $myIP,$gameDisplayName) -fileName ('{0}\qr\{1}.png' -f $PSScriptRoot,$gameDisplayName)|out-null

I changed it to

    Write-Output ('{0} Making QR code for {1}' -f $(Get-Date -Format s),$3dsCiafile.name)
    New-QR -Message ('http://{0}:8080/cias/{1}' -f $myIP,$3dsCiafile.name) -fileName ('{0}\qr\{1}.png' -f $PSScriptRoot,$3dsCiafile.name)|out-null		
    #Make game names display in the list as more readable, and removing our reformatting.  
    $gameDisplayName = get-CleanGamename($3dsCiafile.name)   

Now it shows the QR codes on the page and they work with FBI

**Comment by Engarak** [comment]
@Kirezar , you're exactly right.  I used the wrong variable (cleaned display name vs file name), so I corrected it and made the attached miiShop.ps1.  Once again, something that happens with coding way to late into the night.  

If this works for you, @Sabre8073, let me know and I'll make a 0.2.6.2 release to fix this for others as well.  Thanks both of you!

[miishop0.2.6.2.zip](https://github.com/Engarak/MiiShop/files/3169682/miishop0.2.6.2.zip)

**Comment by Sabre8073** [comment]
Tried with the new miishop.ps1 file and the results are the same, no QR codes on localhost, IP address, and QRs don't work in folder.

**Comment by Kirezar** [comment]
Yup same. Looking at your code, you only changed one of the gameDisplayname variables.

` New-QR -Message ('http://{0}:8080/cias/{1}' -f $myIP,$3dsCiafile.name) -fileName ('{0}\qr\{1}.png' -f $PSScriptRoot,$gameDisplayName)|out-null #Thanks for the correction Kirezar! (https://github.com/Kirezar)`

should be

` New-QR -Message ('http://{0}:8080/cias/{1}' -f $myIP,$3dsCiafile.name) -fileName ('{0}\qr\{1}.png' -f $PSScriptRoot,$3dsCiafile.name)|out-null #Thanks for the correction Kirezar! (https://github.com/Kirezar)`

**Comment by Sabre8073** [comment]
Editing the misshop.ps1 file with Kirezar's suggestion has the QRs on the localhost website but I get a Failled to install from URL error from FBI

**Comment by Engarak** [comment]
Ok, @Kirezar , I think I caught everything this time.  Sorry I didn't catch that sooner,  but my environment is currently set for the next version so I'm testing very minimally.

@Sabre8073  Can you try 2 things?  See if this version ([miishop0.2.6.2.zip](https://github.com/Engarak/MiiShop/files/3170957/miishop0.2.6.2.zip)) helps fix the issue or not.  Also, if you still have the issue, see if the URL shown on the 3DS when you scan the QR code works if you type it into a computer.

**Comment by Sabre8073** [comment]
3ds still refuses to download, and visiting the ip address from PC yields hex characters.

**Comment by Engarak** [comment]
@Sabre8073 , so it looks like miiShop is working, because the hex characters you're seeing are most likely the file itself...can you try using this version of posh_server helps with that?  
[PoSHServer-Standalone.zip](https://github.com/Engarak/MiiShop/files/3185126/PoSHServer-Standalone.zip)

**Comment by Sabre8073** [comment]
@Engarak, that didn't fix my issue unfortunately

**Comment by Engarak** [comment]
Ok @Sabre8073, I'm about to release a new version this weekend (0.2.7).  When it's out (I'll let you know)  I'll ask that you try that new version out to see if it resolves the issues you're having as I have made a good number of improvements that may resolve the issues you're having.  Right after I release the new version, I'll close this issue.  Then if you're having problems still after that you can open the issue against the new version.  I appreciate your patience with this process, it's just that don't have enough time to supporting the older version and the new version.

**Comment by Sabre8073** [comment]
@Engarak, sounds good!

**Comment by Engarak** [comment]
So I just released the new version, here ->https://github.com/Engarak/miiShop_Install/releases/tag/0.2.7

Please try an upgrade first, selecting the location of the `miiShop.ps1` file when asked.  I think it should work for you (from my testing of a 0.2.6.2 to 0.2.7 upgrade).  If that does not work, try this process:
1. Delete everything other than your cias folder where miiShop.ps1 is
1. Move all of the .cia files from the cias folder to the folder where the miiShop.ps1 file was
1. Delete the empty cias folder (don't delete it if there are files left, I don't want you to lose games!)
1. Re-run the install/upgrade file but choosing to do an install
1. When asked where your CIA files are, provide the location you just moved the cias to

This will rebuild the whole library and rescan everything.  It's the nuclear option, but I hope it works for you.
