### ISSUE TITLE
 recognition of roms CIA

### ISSUE THREAD

**Issue by braddocksp** [Engarak/MiiShop#2]
The actual recognition is bad, need to implement some system to read de CIA ID or serial of game (and unique value), using only the name is difficult.

**Comment by Engarak** [comment]
I understand that it's not as good as I'd really want, but this is the same method other popular applications use like Plex, Kodi, and such,  While it's not an exact science, it's all I can really do with my current skills and the tools I can find.  You're welcome to pull the script from the repo, add the improved database matching and send it back for my review, so I can check it in.  I'll gladly take any improvements you'd like to offer.

**Comment by braddocksp** [comment]
You dont need change too much, and idea is dont use name,use titleid or serial (you are using http://3dsdb.com/database and have this information). And later the only we need to put the titleid or serial in the files. Is posible¿?

**Comment by Engarak** [comment]
Sorry for my defensive tone in my prior reply, I didn't react well to the valid criticism, and that's not fair to you. 
 So, I'm Sorry I was a bit callous.  

...but back to the question.  

It would still be doable, but i didn't think of it that way when I did what I did for game detection. 
 I'd still be following my same scheme to store for a reference to at least detect game in the DB and add the titleid or serial to the game name,  

But, good news! I'm already doing a similar thing for next release to start making a "database" to track game information in an effort to not rename the games but track some extra values to match it in the database.  This will give the same affect, as I can make it manually editable.  Did you not get a match? Well, you'll then be able to add your own box art link, serial to re-look up the game or what have you.  This way you'll have it look how you want, when you want. 

Oh, and the ability to adjust settings for miiShop in the web page, is coming too.  Need a new web server port? Bam, you can make that happen.  Thinking of a new background? Just change the link to another image.  

This is needed for my own sanity, but also to help others who need some quality of life changes.  Good thing, this is a comment on a closed ticket....else too many people may find out and bug me.  👍

**Comment by Engarak** [comment]
Leaving closed as this is in progress in a different manner, see above for reason...

**Comment by braddocksp** [comment]
Dont worry, my english is bad and sometimes sounds very directly, but that not was my intention.

And for the question, is great these things make very complete "system" to make a private collection of 3ds games. The idea to make editable or posibility to add manual is good, and supply the problems of autodection or naming.

And thanks for the program, is a good idea, the most people are only interested in senders cia apps, but your idea is great for people than me, i like to make my collection (all 3ds games:P) easy accesible.
