### ISSUE TITLE
QR codes over public IP

### ISSUE THREAD

**Issue by Test0004** [Engarak/MiiShop#4]
Is it possible to have a setting in the config to change the QR codes to the Host's public IP? It would be nice to be able to remotely access the web server and install games.

**Comment by Test0004** [comment]
Never mind; I'm an idiot. Please ignore.

**Comment by Test0004** [comment]
Never mind; I'm an idiot. Please ignore.

**Comment by Test0004** [comment]
Oops, accidentally closed this.

**Comment by Engarak** [comment]
Let me first say, thanks for your patience.  After I released the last version i took some time off for spending with the family, so I didn't get to this as quick as I wanted.  That said, I can do this feature request, but my fear is people will use it to setup a game server with multiple people on the internet, in a pirating measure.  The intent of this application is to share your own collection to your 3DS of games you own. I'd like to do this to help, but doing something that would help you currently would open this to piracy.

**Comment by Engarak** [comment]
Closing this due to not being possible due to piracy concerns.
