### ISSUE TITLE
Enhancement: RaspberryPi

### ISSUE THREAD

**Issue by deltaFigure** [Engarak/MiiShop#5]
Hi, i was wondering if you intend to add support for the raspberry pi,
It would be nice if i can have my game library hosted on there since it's a lot smaller and uses a lot less energy.
Instead of needing to have a pc/laptop running this.

**Comment by Engarak** [comment]
Let me first say, thanks for your patience. After I released the last version i took some time off for spending with the family, so I didn't get to this as quick as I wanted. That said, I'm looking at powershell core support (it's on my project board), which should let it work on RPi I believe.  It's planned for a future version probably, 0.3.0 to bring this support.  Going to close this as I don't have a timeline but the feature is coming!
