### ISSUE TITLE
Unable to connect [FIREFOX 70.0.1] 0.2.9

### ISSUE THREAD

**Issue by AL3XPI** [Engarak/MiiShop#7]
I have setup everything correctly, following the instructions. I added a game to the base directory (one with miiShop.ps1), and I built a new main page many times, yet, each time I start the server, and am sent to localhost:80/main.html I recieve this error:
![image](https://user-images.githubusercontent.com/35903333/69908100-b03a3d00-13b0-11ea-8746-ca4b55f61f93.png) 
I have tried rebuilding and reinstalling many times. Please help.

**Comment by Masamune3210** [comment]
Protip, local IP addresses mean nothing to anyone outside of your network. You don't have to blank it out

**Comment by AL3XPI** [comment]
Thank you. I checked nginx logs, and each time I run the server it says unknown directive : "worker_processes". in the nginx.conf file. Maybe you need to reconfig it?

**Comment by Engarak** [comment]
Thanks for your patience while I was busy!  To see if nginx is actually running try this:
1. Open Task Manager (right click on a blank area of your start bar and choose Task Manager)
1. Go to the Processes tab 
1. Click on the name column (this sorts the list in alphabetical order)
1. Scroll down and try to see if nginx.exe is running in the list

I expect you won't find it in the list of running processes , which means it's failing to start for one reason or another, and my logs should help from there.  To check them, look in the logs folder where miishop.ps1 is.  You can try to review the logs, or you can send them to me (use a service like [pastebin ](https://pastebin.com/) and link them here for example) as it will give me some details so I can help you.  From there I can hopefully help figure out what is going on.

**Comment by Engarak** [comment]
any update @AL3XPI ?  I'll gladly help, I just haven't heard from you.  If I don't hear from you by 12/15/2019 I'll assume the issue got resolved, and will close this issue.

**Comment by Engarak** [comment]
No response from the user, closing
